#!/bin/bash
VIDEO_URL=$1
YTDL_PATH=$(which youtube-dl)

if [ -z "$(which ffmpeg)" ]
then
	echo "Please consider to install 'ffmpeg' to merge audio and video together"
fi

if [ -n "$YTDL_PATH" ]
then
	if [ -n "$VIDEO_URL" ]
	then
		RESULT=$($YTDL_PATH -F "$VIDEO_URL")
		if [[ -n $RESULT ]]
		then
			shift
			var="$YTDL_PATH -F $VIDEO_URL | awk '{print \$1}'"
			#######
			for (( ; ; ))
			do
				if [ "$(($(eval $(echo $var | grep 137))))" -eq "$((137))" ]
				then
					echo "Descargando en FHD"
					$YTDL_PATH -f 137+140 --merge mp4 -o '%(title)s.%(ext)s' "$VIDEO_URL"
					break
				fi

				if [ "$(($(eval $(echo $var | grep 136))))" -eq "$((136))" ]
				then
					echo "Descargando en HD"
					$YTDL_PATH -f 136+140 --merge mp4 -o '%(title)s.%(ext)s' "$VIDEO_URL"
					break
				fi

				if [ "$(($(eval $(echo $var | grep 134))))" -eq "$((134))" ]
				then
					echo "Descargando en SD";
					$YTDL_PATH -f 134+140 --merge mp4 -o '%(title)s.%(ext)s' "$VIDEO_URL"
					break
				fi

				if [ "$(($(eval $(echo $var | grep 133))))" -eq "$((133))" ]
				then
					echo "Descargando en LD";
					$YTDL_PATH -f 133+140 --merge mp4 -o '%(title)s.%(ext)s' "$VIDEO_URL"
					break
				fi

			done

		fi
	else
		echo -e "Please insert a valid youtube video\nUsage: download_youtube https://www.youtube.com/watch?v=mK6sf5YX9ds\nOr: download_youtube https://youtu.be/mK6sf5YX9ds"
	fi
else
	echo -e "Please save the youtube-dl full path using the command:\nexport $YTDL_PATH=/path/to/youtube-dl"
fi
